import {
  MdDevices,
  MdCheckroom,
  MdHome,
  MdSportsSoccer,
  MdFaceRetouchingNatural,
  MdMenuBook,
  MdToys,
  MdPets,
  MdDirectionsCar,
  MdRestaurant,
  MdHealthAndSafety,
  MdBuild,
} from "react-icons/md";

export const menus = [
  { href: "/", label: "Home", active: true },
  { href: "/products", label: "Products" },
  { href: "/aboutUs", label: "About Us" },
  { href: "/contactUs", label: "Contact Us" },
  { href: "#", label: "Our Clients" },
];

export const categories = [
  {
    id: 1,
    name: "Electronics",
    icon: <MdDevices size={20} />,
    subcategories: [
      "Smartphones",
      "Laptops",
      "Tablets",
      "Smart Watches",
      "Cameras",
      "Headphones",
      "Smart TVs",
      "Gaming Consoles",
    ],
  },
  {
    id: 2,
    name: "Fashion",
    icon: <MdCheckroom size={20} />,
    subcategories: [
      "Men's Clothing",
      "Women's Clothing",
      "Kids' Fashion",
      "Footwear",
      "Bags & Wallets",
      "Jewellery",
      "Sunglasses",
      "Watches",
    ],
  },
  {
    id: 3,
    name: "Home & Garden",
    icon: <MdHome size={20} />,
    subcategories: [
      "Furniture",
      "Bedding",
      "Kitchen",
      "Lighting",
      "Garden Tools",
      "Storage",
      "Curtains",
      "Bath Accessories",
    ],
  },
  {
    id: 4,
    name: "Sports",
    icon: <MdSportsSoccer size={20} />,
    subcategories: [
      "Gym Equipment",
      "Outdoor Sports",
      "Cycling",
      "Swimming",
      "Yoga & Fitness",
      "Team Sports",
      "Climbing",
      "Running",
    ],
  },
  {
    id: 5,
    name: "Beauty",
    icon: <MdFaceRetouchingNatural size={20} />,
    subcategories: [
      "Skincare",
      "Haircare",
      "Makeup",
      "Fragrances",
      "Nail Care",
      "Men's Grooming",
      "Organic Products",
    ],
  },
  {
    id: 6,
    name: "Books",
    icon: <MdMenuBook size={20} />,
    subcategories: [
      "Fiction",
      "Non-Fiction",
      "Children's Books",
      "Textbooks",
      "Comics",
      "Self-Help",
      "Science",
      "Biographies",
    ],
  },
  {
    id: 7,
    name: "Toys & Games",
    icon: <MdToys size={20} />,
    subcategories: [
      "Action Figures",
      "Board Games",
      "Puzzles",
      "Educational Toys",
      "Remote Control",
      "Dollhouses",
      "Art Supplies",
    ],
  },
  {
    id: 8,
    name: "Pets",
    icon: <MdPets size={20} />,
    subcategories: [
      "Dog Supplies",
      "Cat Supplies",
      "Bird Supplies",
      "Fish & Aquatics",
      "Small Pets",
      "Pet Food",
      "Grooming",
    ],
  },
  {
    id: 9,
    name: "Automotive",
    icon: <MdDirectionsCar size={20} />,
    subcategories: [
      "Car Accessories",
      "Motorcycle",
      "Car Care",
      "Tools",
      "Tyres",
      "GPS & Navigation",
      "Seat Covers",
    ],
  },
  {
    id: 10,
    name: "Food & Grocery",
    icon: <MdRestaurant size={20} />,
    subcategories: [
      "Fresh Produce",
      "Dairy",
      "Snacks",
      "Beverages",
      "Organic",
      "Frozen Foods",
      "Bakery",
      "International",
    ],
  },
  {
    id: 11,
    name: "Health",
    icon: <MdHealthAndSafety size={20} />,
    subcategories: [
      "Vitamins",
      "Medical Devices",
      "Personal Care",
      "Wellness",
      "First Aid",
      "Weight Management",
    ],
  },
  {
    id: 12,
    name: "Tools & DIY",
    icon: <MdBuild size={20} />,
    subcategories: [
      "Power Tools",
      "Hand Tools",
      "Electrical",
      "Plumbing",
      "Painting",
      "Safety",
      "Measuring Tools",
    ],
  },
];
